# This file was generated by GoReleaser. DO NOT EDIT.
cask "gascity" do
  name "gascity"
  desc "Gas City CLI — an orchestration-builder SDK for multi-agent coding workflows"
  homepage "https://github.com/gastownhall/gascity"
  version "0.13.1-rc5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gc"

  on_macos do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "c01054b8eee2dc06f1286b1834a00f2abd93b8100d754c38eb2d6becd1dbf559"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "7a1c6df009855fb65b61b9d4e4f2dbb2853d8dfe93b66b174397b5177b9d6512"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "d0538fda3512b3869532945536b7796169eeaeca80256fd8a42d0a3f2984f7fe"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "2d69d856815f2f95dee2c5c256a030c5b5ad508428ba4e1ca5c97b2fc5e8d9a3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gc"]
    end
  end

  # No zap stanza required
end
