# This file was generated by GoReleaser. DO NOT EDIT.
cask "gascity" do
  name "gascity"
  desc "Gas City CLI — an orchestration-builder SDK for multi-agent coding workflows"
  homepage "https://github.com/gastownhall/gascity"
  version "0.13.1-rc3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gc"

  on_macos do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "f63073c8e72b1c99665f3a68f09ba7a39d6586d332fd8c90fdd66d758680c87f"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "59e64be089f1c9fac41582b8af1823989f142a66c6ec9044335d1c5f814aec1d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "cfb6344cdb062fbee6c03986db2393531d5cf3d7be5750ac1c6ce3bc9c83fb4c"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "275d38d941fd71cca1ec97372de0b921ecc4ce229a7b9ce391fa1a507305faf3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gc"]
    end
  end

  # No zap stanza required
end
