# This file was generated by GoReleaser. DO NOT EDIT.
cask "gascity" do
  name "gascity"
  desc "Gas City CLI — an orchestration-builder SDK for multi-agent coding workflows"
  homepage "https://github.com/gastownhall/gascity"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gc"

  on_macos do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "cd3d7834ee8b6c3036084d2c5acf033f21cd60b3f4855acb23f04e868ca83509"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "2dc7a3867e6ea0c6f2c876086ffb18d96da86ccdfce7dce8d9e2fca5747f0f3d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_amd64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "3fc85ff4e8a3f0841771dd0d8a98a8ff6ce681266dc80fca8dca8f61f0be1a1e"
    end
    on_arm do
      url "https://github.com/gastownhall/gascity/releases/download/v#{version}/gascity_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gastownhall/gascity/"
      sha256 "c745dcad40a850bd0a490451ead6ad2e9203d2b61ee6684aae4f5682f03ad4e6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gc"]
    end
  end

  # No zap stanza required
end
