# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gascity < Formula
  desc "Gas City CLI — an orchestration-builder SDK for multi-agent coding workflows"
  homepage "https://github.com/gastownhall/gascity"
  version "0.13.1-rc9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.1-rc9/gascity_0.13.1-rc9_darwin_amd64.tar.gz"
      sha256 "31a0483ceb48ae1321aecbcbbdb491d6dc49b1b87f128584189480b739c5bd8b"

      define_method(:install) do
        bin.install "gc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.1-rc9/gascity_0.13.1-rc9_darwin_arm64.tar.gz"
      sha256 "e572107c0b897fa54fb49e9d202d2dc5f6657ea4070e7265c3a7cb7fd51dcdeb"

      define_method(:install) do
        bin.install "gc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.1-rc9/gascity_0.13.1-rc9_linux_amd64.tar.gz"
      sha256 "cd489d81aa1b0da39064ea7046cda91738c4988a9ca2a56b7b236b66b45c9bb4"
      define_method(:install) do
        bin.install "gc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.1-rc9/gascity_0.13.1-rc9_linux_arm64.tar.gz"
      sha256 "a23792dfd57327b0c136de8130ce476a48eb282084ac78897d0e5927dc233e65"
      define_method(:install) do
        bin.install "gc"
      end
    end
  end

  service do
    run [opt_bin/"gc", "supervisor", "run"]
    keep_alive true
    log_path var/"log/gascity/supervisor.log"
    error_log_path var/"log/gascity/supervisor.err.log"
    working_dir var/"lib/gascity"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gc version")
  end
end
