# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gascity < Formula
  desc "Gas City CLI — an orchestration-builder SDK for multi-agent coding workflows"
  homepage "https://github.com/gastownhall/gascity"
  version "0.13.3-rc4"
  license "MIT"

  depends_on "beads"
  depends_on "dolt"
  depends_on "flock"
  depends_on "git"
  depends_on "jq"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.3-rc4/gascity_0.13.3-rc4_darwin_amd64.tar.gz"
      sha256 "2075b63a46636990cbdba66b3bb4bc9a973f1ca2e51f9131d870af23f6274a90"

      define_method(:install) do
        bin.install "gc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.3-rc4/gascity_0.13.3-rc4_darwin_arm64.tar.gz"
      sha256 "1ac4b905043a0cd541cc59ad189ebda44769738bb437ad044bd5ceaff61e119c"

      define_method(:install) do
        bin.install "gc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.3-rc4/gascity_0.13.3-rc4_linux_amd64.tar.gz"
      sha256 "937026d889fd41c71f98aac09c240bb9c0639cbc59bfcdbd4c8c5c87ddfe9cc0"
      define_method(:install) do
        bin.install "gc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gastownhall/gascity/releases/download/v0.13.3-rc4/gascity_0.13.3-rc4_linux_arm64.tar.gz"
      sha256 "11e95e4ca7823f27fa0251f0ff01ab776046abdb9fd513602aa466ccfacf9518"
      define_method(:install) do
        bin.install "gc"
      end
    end
  end

  def caveats
    <<~EOS
      Dependencies (tmux, jq, git, dolt, flock) are installed automatically.

      To start the Gas City supervisor (auto-registers as a login service):
        gc start <city-path>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gc version")
  end
end
